"""Sets the two halves of the double run against each other: a migration instrument.

Usage, from this directory's package root (`apps/miaotou_app`):

    python3 tool/double_run/compare.py [--dart-bin dart] [--report tool/double_run/report.md]

It runs both probes, pairs every fixture by id, compares the conclusions with
the wording left out, and writes `report.md`. It exits non-zero when a
divergence has no explanation in `known_divergences.json`, which is the point:
the instrument is allowed to find differences, it is not allowed to leave them
unaccounted for.

`--self-check` poisons one conclusion on purpose and asserts that the comparison
reports it. A comparator that agreed with everything would still print a green
report, so this is the mutation the instrument is given before it is trusted.
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parents[1]  # tool/double_run → tool → miaotou_app

# What each area compares, and against which existing implementation. Spelled
# here so the report can say what was covered without anyone re-reading probes.
SOURCES = {
    'injection': ('#10', 'suspectInjectionTexts / otherRecentTexts / sanitizeCandidateTexts',
                  'jev_windows/core/draft.py: _suspects / _her_recent / _sanitize'),
    'advice': ('#7', 'parseAdvice', 'jev_mac/core.py: parse_advice'),
    'rewrite': ('#7', 'parseRewrite', 'jev_mac/core.py: parse_rewrite'),
    'scoring': ('#7', 'applyScores', 'jev_mac/ranking.py: apply_scores'),
    'chat_csv': ('#8', 'readChatCsv', 'jev_mac/trend.py: load_csv'),
    'profile': ('#9', 'validateProfile / profileContext',
                'jev_mac/experience.py: validate_profile / profile_context'),
    'update': ('#10', 'newerRelease', 'jev_windows/app/update.py: parse_version + check_latest'),
    'csv_grid': ('#8', 'writeCsvGrid / parseCsvGrid (round trip)', "Python's csv module"),
}


def canon(value):
    """The conclusion, with nothing in it that is only an encoding choice.

    Key order differs between `jsonEncode` and `json.dumps`, and a whole float
    is the same number as the int the other side wrote; neither is a divergence.
    """
    if isinstance(value, dict):
        return {key: canon(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [canon(item) for item in value]
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return value


def run(arguments, cwd):
    result = subprocess.run(arguments, cwd=str(cwd), capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f'probe failed: {" ".join(arguments)}')
    return json.loads(result.stdout)


def compare(dart, python):
    """Pairs every area's fixtures by id and returns the differing ones."""
    divergences = []
    for area in sorted(SOURCES):
        left = {row['id']: row for row in dart[area]}
        right = {row['id']: row for row in python[area]}
        for key in sorted(set(left) | set(right)):
            if key not in left or key not in right:
                divergences.append((area, key, left.get(key), right.get(key)))
                continue
            if canon(left[key]) != canon(right[key]):
                divergences.append((area, key, left[key], right[key]))
    return divergences


def self_check(dart, python):
    """Poisons one conclusion and insists the comparator notices."""
    poisoned = json.loads(json.dumps(dart))
    poisoned['injection'][0]['survivors'] = ['poisoned']
    if not compare(poisoned, python):
        raise SystemExit('self-check failed: a poisoned conclusion compared equal')
    return 'self-check: one poisoned conclusion was reported as a divergence'


def report_markdown(divergences, known, counts):
    lines = ['# Dart ↔ Python double run', '',
             'Generated by `compare.py`. Do not hand-edit: change the fixtures or '
             'the implementations and run it again.', '',
             '## What was compared', '',
             '| Area | Ticket | Dart | Python |',
             '| --- | --- | --- | --- |']
    for area, (ticket, dart_side, python_side) in SOURCES.items():
        lines.append(f'| `{area}` | {ticket} | {dart_side} | `{python_side}` |')
    lines += ['', '## Result', '',
              '| Area | Fixtures | Agree | Divergent |', '| --- | --- | --- | --- |']
    for area in sorted(SOURCES):
        agreed = counts[area] - sum(1 for item in divergences if item[0] == area)
        lines.append(f'| `{area}` | {counts[area]} | {agreed} | '
                     f'{counts[area] - agreed} |')
    total = sum(counts.values())
    lines += ['', f'{total} fixtures, {len(divergences)} divergent.', '']

    explained = [item for item in divergences if f'{item[0]}/{item[1]}' in known]
    unexplained = [item for item in divergences if f'{item[0]}/{item[1]}' not in known]

    lines += ['## Explained divergences', '']
    if not explained:
        lines.append('None.')
    for area, key, left, right in explained:
        lines += [f'### `{area}/{key}`', '', known[f'{area}/{key}'], '',
                  '```json',
                  'dart:   ' + json.dumps(canon(left), ensure_ascii=False, sort_keys=True),
                  'python: ' + json.dumps(canon(right), ensure_ascii=False, sort_keys=True),
                  '```', '']

    lines += ['## Unexplained divergences', '']
    if not unexplained:
        lines.append('None. This is the state the instrument must be left in '
                     'before any port is deleted.')
    for area, key, left, right in unexplained:
        lines += [f'### `{area}/{key}`', '', '```json',
                  'dart:   ' + json.dumps(canon(left), ensure_ascii=False, sort_keys=True),
                  'python: ' + json.dumps(canon(right), ensure_ascii=False, sort_keys=True),
                  '```', '']
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dart-bin', default='dart')
    parser.add_argument('--report', default=str(HERE / 'report.md'))
    parser.add_argument('--self-check', action='store_true')
    args = parser.parse_args()

    dart = run([args.dart_bin, 'run', 'tool/double_run/probe.dart'], PACKAGE)
    python = run([sys.executable, 'tool/double_run/probe.py'], PACKAGE)
    known = json.loads((HERE / 'known_divergences.json').read_text(encoding='utf-8'))
    counts = {area: len(dart[area]) for area in SOURCES}
    divergences = compare(dart, python)

    if args.self_check:
        print(self_check(dart, python))
        return

    Path(args.report).write_text(
        report_markdown(divergences, known, counts), encoding='utf-8')
    print(f'{sum(counts.values())} fixtures, {len(divergences)} divergent '
          f'({sum(1 for d in divergences if f"{d[0]}/{d[1]}" in known)} explained)')
    unexplained = [d for d in divergences if f'{d[0]}/{d[1]}' not in known]
    for area, key, _, _ in unexplained:
        print(f'unexplained: {area}/{key}')
    if unexplained:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
